### ISSUE TITLE
Changing Center Frequency

### ISSUE THREAD

**Issue by minkione** [HackingIntoYourHeart/HackRF-Portapack-DeBruijn#1]
Hi,
Very cool idea. Was wondering if you could provide the steps used to generate them.
I noticed the center frequency is 315MHz, however I wanted to try those files against my testing setup (RF relay working on 433MHz).

Thanks

**Comment by dabm-git** [comment]
> Hi,
> Very cool idea. Was wondering if you could provide the steps used to generate them.
> I noticed the center frequency is 315MHz, however I wanted to try those files against my testing setup (RF relay working on 433MHz).
> 
> Thanks

Just change `center_frequency=315000000 ` to  `433000000 `

**Comment by HackingIntoYourHeart** [comment]
> Hi,
> Very cool idea. Was wondering if you could provide the steps used to generate them.
> I noticed the center frequency is 315MHz, however I wanted to try those files against my testing setup (RF relay working on 433MHz).
> 
> Thanks

In the "Replay" menu of the Havoc or Mayhem firmware you can manually change the frequency. Yes, you can change the frequency through the .txt files, however it can be done manually on the Portapack
